% CZ bring up:
%%
setQSettings('r_avg',5000);
acz_ampLength('controlQ','q7','targetQ','q8',...
       'dataTyp','Phase',...
       'czLength',[200],'czAmp',[2.65e4:50:2.95e4],'cState','1',...
       'notes','','gui',true,'save',true);
%% check |11> -> |02> state leakage, method: prepare |11>, apply CZ, measure P|0?>
setQSettings('r_avg',5000);
acz_ampLength('controlQ','q7','targetQ','q8',...
       'dataTyp','P',...
       'czLength',[60:10:350],'czAmp',[2.55e4:100:2.95e4],'cState','1',...
       'notes','','gui',true,'save',true);
%%
setQSettings('r_avg',1000);
temp.czRBFidelityVsPhase('controlQ','q7','targetQ','q8',...
      'phase_c',[-pi:2*pi/10:pi],'phase_t',[-pi:2*pi/10:pi],...
      'numGates',4,'numReps',20,...
      'notes','','gui',true,'save',true);
%%
sqc.measure.gateOptimizer.czOptPhase({'q7','q8'},4,20,1500, 50);
%%
qc.measure.gateOptimizer.czOptPhaseAmp({'q7','q8'},4,20,1500, 100);
%%
setQSettings('r_avg',1000);
temp.czRBFidelityVsPlsCalParam('controlQ','q7','targetQ','q8',...
       'rAmplitude',[-0.02:0.005:0.03],'td',[464],'calcControlQ',false,...
       'numGates',4,'numReps',20,...
       'notes','','gui',true,'save',true);