q = 'q1';
numGates = 100;
[Pref,Pgate] = data_taking.public.xmon.randBenchMarking('qubit1',q,'qubit2',[],...
       'process','X/2','numGates',numGates,'numReps',10,...
       'gui',true,'save',true);   