setQSettings('r_avg',5000,'q8');
setQSettings('r_avg',5000,'q9');
CZTomoData = Tomo_2QProcess('qubit1','q9','qubit2','q8',...
'process','CZ','reps',1,...
'notes','','gui',true,'save',true);

setQSettings('r_avg',10000,'q8');
setQSettings('r_avg',10000,'q9');
CZTomoData = Tomo_2QProcess('qubit1','q9','qubit2','q8',...
'process','CZ','reps',1,...
'notes','','gui',true,'save',true);